# Generated by Django 4.1.6 on 2023-02-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionarioFabrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('rg', models.CharField(blank=True, max_length=150, null=True, verbose_name='RG')),
                ('cpf', models.CharField(blank=True, max_length=150, null=True, verbose_name='CPF')),
                ('data_admissao', models.DateField(auto_now=True, null=True, verbose_name='Data de admissão')),
                ('data_hora_alteracao_do_registro', models.DateTimeField(auto_now=True, null=True, verbose_name='Data e hora da alteração do registro')),
                ('cep', models.CharField(blank=True, max_length=50, null=True, verbose_name='CEP')),
                ('endereco', models.CharField(blank=True, max_length=250, null=True, verbose_name='Endereço')),
                ('bairro', models.CharField(blank=True, max_length=250, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=250, null=True, verbose_name='Cidade')),
            ],
        ),
    ]
